// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqpdenyxmnjyioerivdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxcGRlbnl4bW5qeWlvZXJpdmR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTc5NjEsImV4cCI6MjA2NjY3Mzk2MX0.a2mLhBP8bTGumONzliRxXhDySXT1FwlYwbHO28-VRgQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);